Raise memlock to 16M for io_uring testing
When we create several Vert.x instances (e.g. in clustering tests), the required amount of locked memory easily goes beyond the limits (8MB on modern Linux).

This is to avoid failures like:

```
java.lang.IllegalStateException: failed to create a child event loop
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:92)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:53)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.netty.channel.MultiThreadIoEventLoopGroup.<init>(MultiThreadIoEventLoopGroup.java:104)
        at io.vertx.core.spi.transport.Transport.eventLoopGroup(Transport.java:92)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:221)
        at io.vertx.core.impl.VertxBootstrapImpl.instantiateVertx(VertxBootstrapImpl.java:249)
        at io.vertx.core.impl.VertxBootstrapImpl.vertx(VertxBootstrapImpl.java:265)
        at io.vertx.core.Vertx$1.build(Vertx.java:143)
        at io.vertx.test.core.VertxTestBase.createVertx(VertxTestBase.java:317)
        at io.vertx.test.core.VertxTestBase.lambda$vertx$2(VertxTestBase.java:330)
        at io.vertx.test.core.VertxTestBase.vertx(VertxTestBase.java:337)
        at io.vertx.test.core.VertxTestBase.vertx(VertxTestBase.java:330)
        at io.vertx.test.core.VertxTestBase.setUp(VertxTestBase.java:240)
        at io.vertx.test.core.AsyncTestBase.before(AsyncTestBase.java:78)
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Cannot allocate memory
        at io.netty.channel.uring.Native.ioUringSetup(Native Method)
        at io.netty.channel.uring.Native.createRingBuffer(Native.java:402)
        at io.netty.channel.uring.IoUringIoHandler.<init>(IoUringIoHandler.java:106)
        at io.netty.channel.uring.IoUringIoHandler$1.newHandler(IoUringIoHandler.java:708)
        at io.netty.channel.SingleThreadIoEventLoop.<init>(SingleThreadIoEventLoop.java:105)
        at io.netty.channel.MultiThreadIoEventLoopGroup.newChild(MultiThreadIoEventLoopGroup.java:212)
        at io.netty.channel.MultiThreadIoEventLoopGroup.newChild(MultiThreadIoEventLoopGroup.java:198)
        at io.netty.channel.MultiThreadIoEventLoopGroup.newChild(MultiThreadIoEventLoopGroup.java:35)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
        ... 45 more
```

Another option could be to configure the sizes of the ring and completion queue with netty sysprops.

Signed-off-by: Thomas Segismont <tsegismont@gmail.com>